---
- name: Configure Proxy Server
  hosts: proxy_server
  become: yes

  tasks:

    - name: Install nginx
      apt:
        name: nginx
        state: present
        update_cache: yes


    - name: Copy nginx config
      copy:
        src: nginx.conf
        dest: /etc/nginx/sites-available/default


    - name: Restart nginx
      service:
        name: nginx
        state: restarted